# Generated by Django 4.1.7 on 2023-03-06 18:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("AppointmentID", models.AutoField(primary_key=True, serialize=False)),
                ("Start", models.DateTimeField()),
                ("End", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("Code", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.TextField()),
                ("Brand", models.TextField()),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "AadharId",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("Name", models.TextField()),
                ("Address", models.TextField()),
                ("Phone", models.TextField()),
                ("Email", models.TextField()),
                (
                    "Gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "male"), (2, "female"), (3, "other")]
                    ),
                ),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("Number", models.IntegerField(primary_key=True, serialize=False)),
                ("Type", models.TextField()),
                ("Floor", models.IntegerField()),
                ("Block", models.IntegerField()),
                ("Unavailable", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("Code", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.TextField()),
                ("Description", models.TextField()),
                ("Cost", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                ("TreatmentID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.TextField()),
                ("Cost", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(max_length=64, null=True)),
                ("last_name", models.CharField(max_length=64, null=True)),
                ("email", models.CharField(max_length=64, null=True)),
                ("is_staff", models.CharField(max_length=64, null=True)),
                ("is_active", models.IntegerField(null=True)),
                ("date_joined", models.CharField(max_length=64, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "frontDeskOperator"),
                            (2, "dataOperator"),
                            (3, "doctor"),
                            (4, "admin"),
                        ]
                    ),
                ),
                ("password", models.CharField(max_length=256)),
                ("username", models.CharField(max_length=64, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "EmployeeId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Name", models.TextField()),
                ("Address", models.TextField()),
                ("Phone", models.TextField()),
                ("Email", models.TextField()),
                ("AadharId", models.CharField(max_length=15)),
                (
                    "Gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "male"), (2, "female"), (3, "other")]
                    ),
                ),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DataOperator",
            fields=[
                (
                    "EmployeeId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Name", models.TextField()),
                ("Address", models.TextField()),
                ("Phone", models.TextField()),
                ("Email", models.TextField()),
                ("AadharId", models.CharField(max_length=15)),
                (
                    "Gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "male"), (2, "female"), (3, "other")]
                    ),
                ),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "EmployeeId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Name", models.TextField()),
                ("Address", models.TextField()),
                ("Phone", models.TextField()),
                ("Email", models.TextField()),
                ("AadharId", models.CharField(max_length=15)),
                (
                    "Gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "male"), (2, "female"), (3, "other")]
                    ),
                ),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FdOperator",
            fields=[
                (
                    "EmployeeId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Name", models.TextField()),
                ("Address", models.TextField()),
                ("Phone", models.TextField()),
                ("Email", models.TextField()),
                ("AadharId", models.CharField(max_length=15)),
                (
                    "Gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "male"), (2, "female"), (3, "other")]
                    ),
                ),
                ("DOB", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Undergoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                (
                    "Appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HM_System.appointment",
                    ),
                ),
                (
                    "Treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HM_System.treatment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stay",
            fields=[
                ("StayID", models.AutoField(primary_key=True, serialize=False)),
                ("Start", models.DateTimeField()),
                ("End", models.DateTimeField(null=True)),
                (
                    "Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HM_System.patient",
                    ),
                ),
                (
                    "Room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HM_System.room"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("ReportID", models.AutoField(primary_key=True, serialize=False)),
                ("Date", models.DateTimeField()),
                ("TestResult", models.TextField()),
                (
                    "Appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HM_System.appointment",
                    ),
                ),
                (
                    "Test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HM_System.test"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescribes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Dose", models.TextField()),
                (
                    "Appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HM_System.appointment",
                    ),
                ),
                (
                    "Medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HM_System.medication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="Patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HM_System.patient"
            ),
        ),
        migrations.AddConstraint(
            model_name="undergoes",
            constraint=models.UniqueConstraint(
                fields=("Appointment", "Treatment"), name="second_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="prescribes",
            constraint=models.UniqueConstraint(
                fields=("Appointment", "Medication"), name="first_constraint"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="Doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HM_System.doctor"
            ),
        ),
    ]
